version: "3.8"
services:
  app:
    container_name: things2share_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - "~/.gitconfig:/etc/gitconfig"
    ports:
      - 8080:8000
      - 8443:443
      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    links:
    - db
  db:
    container_name: things2share_db
    #Ici c'est mariadb mais c'est à paramétrer en fonction du besoin
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: things2share
      MYSQL_DATABASE: things2share
      MYSQL_USER: things2share
      MYSQL_PASSWORD: things2share
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: things2share_pma
    image: phpmyadmin/phpmyadmin
    links:
    - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
      restart: 'no'
    ports:
      - 8081:80
  mailer:
    container_name: things2share_mailer
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:
  db-data: null
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
